version: '3'

services:
  frontend:
    build: ./frontend
    container_name: "student-monitor-frontend"
    restart: always
    environment:
      - VIRTUAL_HOST=stdmon.l1zz.ru
      - LETSENCRYPT_HOST=stdmon.l1zz.ru
    expose:
      - 80
    ports:
      - "8080:80"
    networks:
      - internal
      - host_env
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: "student-monitor-backend"
    restart: always
    environment:
      PORT: 3000
      ROOT_USER:     admin
      ROOT_PASSWORD: 12345
    networks:
      - internal
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    container_name: "student-monitor-db"
    environment:
      POSTGRES_USER: student-monitor
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: student-monitor
    expose:
      - 5432
    networks:
      - internal
    volumes:
      - persistent_data:/var/lib/postgresql/data

volumes: 
  persistent_data:

networks:
  internal:
  host_env:
    name: host_env
    external: true